microsoft/Document-Knowledge-Mining-Solution-Accelerator

- App/kernel-memory/service/Abstractions/Constants.cs
- App/kernel-memory/service/Core/Core.csproj
- App/kernel-memory/service/Core/Handlers/KeywordExtractingHandler.cs
#22 
This pull request introduces a new feature for extracting keywords from content. The changes include adding a new prompt for keyword extraction, updating project files to include the new prompt, and modifying the `KeywordExtractingHandler` class to use the new prompt.
Additions to prompt constants and resources:
* [`App/kernel-memory/service/Abstractions/Constants.cs`](diffhunk://#diff-b0e3ee4d1190e8411c98b1fa8a400a14f184dba51620de7929334989c08bb552R166): Added a new constant `PromptNamesExtractKeywords` for the keyword extraction prompt.
* [`App/kernel-memory/service/Core/Core.csproj`](diffhunk://#diff-53b652c5b89484049ffe79250831e573b475661d31432a94b5893226ec13e34fR45): Included the new `extract-keywords.txt` file as an embedded resource.
Modifications to …
> refactor to allowKeywordExtractingHandler to read from prompt txt

- App/frontend-app/src/components/chat/chatRoom.tsx
* The purpose of this PR is to modify the chat UI such that the "Send" button is disabled by default. It will only be enabled once the user enters text into the chat input field. This behavior improves the user experience by preventing users from sending empty messages
The Send button is disabled by default.
The Send button becomes enabled when text is entered.
No breaking changes are introduced in the chat feature.
> fix: Disable Send/Submit Button by Default in Chat Section

- App/kernel-memory/Dockerfile
* Remove the dot and replace it with a colon in the `Dockerfile` to fix the deployment issue.
* Remove the dot and replace it with a colon in the `Dockerfile` to fix the deployment issue. Now working fine.
> fix: added colon in  dockerfile to fix the deployment issue

- README.DEPLOYMENT.md
* This pull request includes a small but important change to the `README.DEPLOYMENT.md` file. The change corrects a typo in the PowerShell script name to ensure the deployment script runs correctly.
* [`README.DEPLOYMENT.md`](diffhunk://#diff-c4975f0698931fbff656291453ae63de3af2a19c7641317af07c2b660e3b21cbL77-R83): Corrected the typo in the PowerShell script name from `resourdedeployment.ps1` to `resourcedeployment.ps1` to avoid execution issues.
Ensure that the typo in the "Execute Deployment Script" section has been corrected.
> docs: Update README.DEPLOYMENT.md

- App/kernel-memory/Directory.Packages.props
* The image file upload was failing due to compatibility issues with the latest version of Microsoft.SemanticKernel.Abstractions.
* Downgraded the package to ensure proper handling of image file uploads.
- Verify that image file uploads (PNG, JPG, and other supported formats) are processed successfully.
- Ensure there are no new dependency conflicts or regressions in other functionalities.
- Validate that all related services continue working as expected after the downgrade.
> fix: Downgrade Microsoft.SemanticKernel.Abstractions to resolve image file upload issue

- App/frontend-app/src/pages/home/home.tsx
The search term should be cleared from the search box.
All documents should be displayed in the list.
Steps to Reproduce:
- Open the DKM (Document Knowledge Mining) web application.
- Upload multiple documents in the Documents section.
- Enter a search term in the search box—the document list filters based on the searched text.
> fix: "Clear All" Button Not Resetting Search Box Text

- App/frontend-app/src/components/documentViewer/documentViewer.tsx
The pop up should show the content of the file and the file should not get downloaded automatically.
- Open the DKM (Document Knowledge Mining) web application.
- Upload .txt file in the Documents section.
- Click on Details button besides the .txt file.
> fix: Text file getting downloaded on click of details button

- App/frontend-app/src/components/documentViewer/documentViewer.tsx
- README.md
* https://dev.azure.com/CSACTOSOL/CSA%20Solutioning/_workitems/edit/17142/
- [x ] Yes
* AI Knowledge tab : when there is more content or lower resolution based on the content the vertical scrollbar should be visible and able to scroll.
> fix: Bug fix(#17142) - AIKnowledge tab scrolling issue

- Deployment/kubernetes/enable_approuting.psm1
* This change removes the usage of the deprecated http_application_routing add-on from the PowerShell deployment script used for provisioning AKS clusters. Microsoft no longer supports enabling this add-on for new clusters, and its presence causes runtime errors during the deployment process. The goal is to ensure smooth, error-free deployments by using only supported features.
- Confirm that AKS cluster deployment completes successfully without the earlier runtime error related to the deprecated add-on.
- Validate that the workloads are deployed correctly and accessible via the intended routing method (e.g., Ingress Controller or Azure Application Gateway).
- Ensure the rest of the script functions as expected and no dependent configurations are …
> fix: Remove Deprecated HTTP Application Routing Add-on from Deployment Script

- Deployment/resourcedeployment.ps1
* Enhance the robustness of the Docker status check logic. The previous implementation relied solely on matching the exact error message "ERROR: error during connect", which was unreliable and could miss actual failures. This update improves reliability by also checking $LASTEXITCODE and matching a broader substring "error during connect" to ensure Docker is properly validated before proceeding with deploymen.
- Stop Docker Desktop and run the script — it should correctly detect that Docker is not running.
- Start Docker Desktop and run again — the check should pass without errors.
- Ensure the deployment is prevented if Docker is not running.
> fix: Improve Docker availability check using exit code and error match

- App/kernel-memory/Directory.Packages.props
- App/kernel-memory/service/Core/DataFormats/Pdf/PdfMarkdownDecoder.cs
… regions
* Switch to the GA version of Azure.AI.DocumentIntelligence. The current beta version is locked to an api-version that only works in a couple of Azure regions. For example, returns a 404 when Document Intelligence is deployed to Australia East.
- [x ] No
https://learn.microsoft.com/en-us/answers/questions/1514842/document-intelligence-ai-returns-404
> fix: Updated to GA of Document Intelligence - beta does not work against all Azure regions

- Deployment/main.bicep
- Deployment/resourcePrefix.bicep
- Deployment/resourcedeployment.ps1
* This PR introduces the ability to reuse existing Azure Resource Groups when deploying infrastructure using Bicep. The key updates include:
- Added `$environmentName` and `$resourceGroupName` as new parameters.
- Modified deployment logic to skip creation of the resource group if it already exists.
- Ensured all resources are deployed within the provided resource group.
- Validated that no duplicate or conflicting resources are created during test deployment.
- Validate deployment succeeds when using an existing Resource Group.
- Confirm no duplicate or conflicting resources are created.
- Ensure parameters environmentName and resourceGroupName are handled correctly in both script and templates.
- Please restart the AKS (Kubernetes) service after …
> feat: Enable Resource Group Reuse via Environment and RG Name Parameters

- App/frontend-app/src/components/chat/chatRoom.tsx
* This PR addresses a bug where the chat input box token counter did not reset when starting a new topic
Changes:
- Added a dynamic 'key' to the Textarea to force remount and reset internal state on new topic.
- Ensured 'textAreaValue' is cleared on new topic click.
- This ensures consistent behavior for users when they start a new chat session.
1. **When you click the "+" (New Topic) button:**
- The input text area is cleared (no residual text remains).
- The character/token counter displays 0/500.
2. **After starting a new topic:**
- Typing into the input box correctly updates the counter from 0/500 upwards.
- Ensure no console errors or warnings appear during this interaction.
> fix: reset chat input character count on "New Topic" button click

- App/frontend-app/src/components/chat/chatRoom.tsx
- Deployment/resourcedeployment.ps1
This PR addresses a UI issue in the DKM chat interface and improves the deployment script to support tenant-specific authentication:
- UI Fix: Token/Character count now resets correctly after each message is sent and a response is received.
- Deployment Update: PowerShell script modified to allow login using a specified tenant ID, improving compatibility in multi-tenant environments
- Token count resets to 0/500 after sending a message and receiving a response
- Chat functionality works as expected with no UI regressions
- PowerShell deployment runs successfully with tenant-specific login
- No impact on users with default single-tenant login
> fix: Token count reset issue in DKM chat UI and enhance deployment script with tenant-specific login

- .github/workflows/CI.yml
* This PR addresses a failure in the CI pipeline caused by the missing AZURE_TENANT_ID input in the workflow file. The issue has been resolved by adding the required secret value under the $input block in the deployment step.
- Ensure AZURE_TENANT_ID is correctly referenced using ${{ secrets.AZURE_TENANT_ID }}
- Validate that the pipeline now runs successfully in the CI
- Confirm other required inputs (AZURE_SUBSCRIPTION_ID, ENVIRONMENT_NAME) are intact
- Check for no unintended changes in the workflow
> fix: CI pipeline failure resolved by adding AZURE_TENANT_ID input to workflow

- .github/workflows/CI.yml
- App/frontend-app/src/components/chat/chatRoom.tsx
- Deployment/resourcedeployment.ps1
- **Enhancement:** The PowerShell deployment script now prompts for and handles the Azure Tenant ID, improving manual deployment flows. It displays the Tenant ID in the summary and ensures accurate authentication.
- **Bug Fix:** Addresses a frontend bug where the chatRoom textarea did not reset properly after sending a message. Also improves error logging in the chatRoom component.
In the deployment script:
- Confirm the script prompts for Tenant ID if not provided.
- Check that Azure login uses the correct Tenant ID in manual mode.
- Ensure the Tenant ID is displayed in the deployment summary.
In the frontend chatRoom:
- Verify the textarea resets after each message.
- Ensure error logs are informative if an API request fails.
> fix: Enhance Deployment Script for Tenant ID Prompt and Fix Chatroom UI Reset Bug

- Deployment/bicep/azurestorageaccount.bicep
* Added minimal TLS version which is a required property as per SFI
* Check the deployment of storage account
> fix: Added Minimal TLS version for storage account

- .github/workflows/broken-links-checker.yml
This pull request adds a new GitHub Actions workflow to check for broken links in markdown files. The workflow is designed to run on pull requests and manual triggers, ensuring that markdown files are free of broken links.
Workflow addition:
* [`.github/workflows/broken-links-checker.yml`](diffhunk://#diff-67e26d77769066e1f1b5633a89f931c691eabfd57782a0767fa13ebb15319af4R1-R57): Introduced a new workflow named "Broken Link Checker" that uses the `lychee-action` to validate links in markdown files. It checks only changed markdown files for pull requests and all markdown files for manual triggers.
* ...
> feat: Add Broken Link Checker workflow for Markdown files

- App/frontend-app/src/components/uploadButton/uploadButton.tsx
Previously uploaded/failed files still visible after reopening the upload document popup
Bug: https://dev.azure.com/CSACTOSOL/CSA%20Solutioning/_workitems/edit/20381
screenshot :
without refresh the page
> fix: Previously uploaded/failed files still visible after reopening the upload document popup

- App/frontend-app/src/components/chat/chatRoom.tsx
* This PR improves the chat room UX by disabling follow-up suggestions while the chat API is responding.
The component already tracked isLoading, but it wasn't applied to the follow-up question click handlers.
Now, follow-up suggestions are disabled during loading, preventing duplicate API calls and improving flow control
- Follow-up questions are clickable after a response is received.
- Follow-up suggestions are disabled only during loading.
- No extra states or incorrect disabling happens.
- Full chat flow (user message → response → follow-up) works correctly.
> fix: Disable follow-up suggestions while chat response is loading

- docs/QuotaCheck.md
* ...
This pull request includes a minor update to the `docs/QuotaCheck.md` file. The change updates the directory path in the documentation to reflect the correct location of the `quota_check_params.sh` script.
* ...
> docs: readme updated

- .github/workflows/Create-Release.yml
* 
This pull request adds a new GitHub Actions workflow for automated release creation, tailored to the `ve-pipeline-changes` branch. The workflow uses semantic release tools to automate versioning, changelog generation, and GitHub release creation based on commit messages.
**Release automation:**
* Added `.github/workflows/Create-Release.yml` to define a workflow that triggers on pushes to the `ve-pipeline-changes` branch, checks out the code, and runs semantic-release with custom commit type sections for release notes.
* Configured permissions and environment variables to enable the workflow to create releases and write to pull requests.
* Integrated the `codfish/semantic-release-action` with plugins for commit analysis, release notes generation, and GitHub release publishing, using the …
> feat: added Create Release Pipeline 

- Deployment/resourcedeployment.ps1
This pull request makes a minor update to the deployment script by standardizing the path format for the `main.bicep` template file. The change replaces backslashes with forward slashes in the `--template-file` argument for both the what-if and actual deployment commands, improving cross-platform compatibility.
- Deployment script improvements:
* Updated the `--template-file` argument in both the what-if (`az deployment group what-if`) and deployment (`az deployment group create`) commands to use `"./main.bicep"` instead of `.\main.bicep`, ensuring consistent path formatting. [[1]](diffhunk://#diff-8efa90352de03fa0a511a5c08f49e4c1ba0224d16bf6facaf7c7ba90524edddbL249-R249) [[2]](diffhunk://#diff-8efa90352de03fa0a511a5c08f49e4c1ba0224d16bf6facaf7c7ba90524edddbL260-R260)
Verify that the …
> fix: Update Bicep file path for cross-platform compatibility in deployment script

- App/frontend-app/src/components/resizer/panelResizer.scss
- App/frontend-app/src/components/resizer/panelResizer.tsx
- App/frontend-app/src/pages/home/home.module.scss
- App/frontend-app/src/pages/home/home.tsx
* 
This pull request introduces a resizable panel feature to the home page, allowing users to adjust the widths of the documents and chat panels interactively. It also adds the ability to collapse and expand the filter panel, improving the flexibility and usability of the layout. The implementation includes a new `PanelResizer` component, corresponding styles, and modifications to the home page logic and layout.
**Resizable Panels and Filter Panel Improvements**
* Added a new `PanelResizer` React component (`panelResizer.tsx`) that enables users to resize the documents and chat panels by dragging a handle, with enforced minimum widths for usability. (`[App/frontend-app/src/components/resizer/panelResizer.tsxR1-R125](diffhunk://#diff-4a0a17a1cbf4abdffaa33d1eeae9df1efa81d856d01041f12f3544df8 …
> feat: Ui Enhancements introduce two Ui changes, Filter section toggle and document section Resizer

- docs/LocalSetupGuide.md
This pull request adds a comprehensive local setup guide for developers. The new documentation outlines step-by-step instructions for configuring both backend and frontend components, including Azure role assignments and environment variable updates for local debugging.
Documentation improvements:
* Added a new `docs/LocalSetupGuide.md` file with detailed instructions for cloning the repository, setting up Visual Studio solutions, verifying configuration files, and setting startup projects for backend services.
* Included guidance on assigning required Azure roles and updating the Kernel Memory endpoint in Azure App Configuration specifically for local development and debugging.
* Provided frontend setup steps, including environment variable configuration, dependency installation, and …
> docs: add local setup guide
